spring.application.name=incident-management

# Configuración de conexión al contenedor Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/opscore_db
spring.datasource.username=brian_dev
spring.datasource.password=opscore_pass

# Flyway ejecutará los scripts SQL que creamos antes automáticamente
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true


# Cambia el puerto del servidor para evitar el conflicto con el 8080
server.port=8081

#Security
security.jwt.access-exp-min=15
security.jwt.refresh-exp-hours=8
jwt.key.private=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUdIQWdFQU1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhCRzB3YXdJQkFRUWc4S1BzUm5zUzh1VE5rRUJRDQoyV0grb3BwR1NpTXFyTUN3M0xmMzNSR284cGloUkFOQ0FBU0ZYYjF2bUhIOFJDcDZidDJJNlVmT3RHREIxbWRvDQpyVDlMQ25VZTdLQk9QYkQ0MjBjRTQyd0FUOFV0cXJkMDQxWHdJNWhwTTZ5amtWc0NIZmVTZ2JiVA0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ0K
jwt.key.public=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWhWMjliNWh4L0VRcWVtN2RpT2xIenJSZ3dkWm4NCmFLMC9Td3AxSHV5Z1RqMncrTnRIQk9Oc0FFL0ZMYXEzZE9OVjhDT1lhVE9zbzVGYkFoMzNrb0cyMHc9PQ0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tDQo=
