spring.application.name=incident-management

# ============================================================
# DATABASE (PostgreSQL)
# ============================================================
spring.datasource.url=${DB_URL_CONTAINER:jdbc:postgresql://localhost:5432/opscore_db}
spring.datasource.username=${DB_POSTGRES_USERNAME:postgres}
spring.datasource.password=${DB_POSTGRES_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# HIKARI CONNECTION POOL (DEFAULT EN SPRING BOOT)
# ============================================================
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=4
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=IncidentHikariPool

# ============================================================
# JPA / HIBERNATE
# ============================================================
spring.jpa.open-in-view=false

# en producción: none o validate (NO update)
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# FLYWAY
# ============================================================
spring.flyway.enabled=true

# ubicación estándar
spring.flyway.locations=classpath:db/migration

# ============================================================
# SERVER
# ============================================================
server.port=8081

# ============================================================
# SECURITY
# ============================================================
security.jwt.access-exp-min=15
security.jwt.refresh-exp-hours=8
jwt.key.private=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUdIQWdFQU1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhCRzB3YXdJQkFRUWc4S1BzUm5zUzh1VE5rRUJRDQoyV0grb3BwR1NpTXFyTUN3M0xmMzNSR284cGloUkFOQ0FBU0ZYYjF2bUhIOFJDcDZidDJJNlVmT3RHREIxbWRvDQpyVDlMQ25VZTdLQk9QYkQ0MjBjRTQyd0FUOFV0cXJkMDQxWHdJNWhwTTZ5amtWc0NIZmVTZ2JiVA0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ0K
jwt.key.public=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWhWMjliNWh4L0VRcWVtN2RpT2xIenJSZ3dkWm4NCmFLMC9Td3AxSHV5Z1RqMncrTnRIQk9Oc0FFL0ZMYXEzZE9OVjhDT1lhVE9zbzVGYkFoMzNrb0cyMHc9PQ0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tDQo=