# ==========================================
# DATABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/opscore_db
spring.datasource.username=brian_dev
spring.datasource.password=opscore_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# HIKARI
# ==========================================
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=4

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANTE PARA data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ==========================================
# FLYWAY
# ==========================================
spring.flyway.enabled=false

# ==========================================
# SERVER
# ==========================================
server.port=8081

# ==========================================
# SECURITY
# ==========================================
spring.security.enabled=false